"""
Django settings for Rathna_Stores project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
from decimal import Decimal
from dotenv import load_dotenv
from django.core.management.utils import get_random_secret_key

# Load environment variables from .env.local
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

def _env_bool(name: str, default: bool = False) -> bool:
    value = str(os.getenv(name, str(default))).strip().lower()
    return value in {"1", "true", "yes", "on"}


# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = _env_bool('DJANGO_DEBUG', False)

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '').strip()

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = get_random_secret_key()
    else:
        raise RuntimeError(
            'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is False.'
        )

# SECURITY WARNING: don't run with debug turned on in production!
default_allowed_hosts = 'localhost,127.0.0.1,0.0.0.0,[::1],.vercel.app'
ALLOWED_HOSTS = [host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', default_allowed_hosts).split(',') if host.strip()]

default_csrf_origins = 'https://*.vercel.app,http://localhost,http://127.0.0.1'
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', default_csrf_origins).split(',') if origin.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'admin.apps.AdminConfig',
    'cakes.apps.CakesConfig',
    'customers.apps.CustomersConfig',
    'cart.apps.CartConfig',
    'chatbot.apps.ChatbotConfig',
]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', True)
    SECURE_HSTS_PRELOAD = _env_bool('DJANGO_SECURE_HSTS_PRELOAD', True)

ROOT_URLCONF = 'Rathna_Stores.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_count',
                'customers.context_processors.customer_auth',
            ],
        },
    },
]

WSGI_APPLICATION = 'Rathna_Stores.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Supabase Configuration
# https://supabase.com/docs/reference/python/introduction

SUPABASE_URL = os.getenv('SUPABASE_URL', '')
SUPABASE_KEY = os.getenv('SUPABASE_KEY', '')
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = os.getenv('OPENROUTER_MODEL', 'cohere/north-mini-code:free')

# A small, process-local cache removes repeated remote reads during normal
# browsing without treating changing cart/order data as permanently fresh.
# Deployments with multiple workers can replace this with a shared Redis cache.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'rathna-stores',
        'TIMEOUT': int(os.getenv('DJANGO_CACHE_TIMEOUT_SECONDS', '30')),
    }
}
STAFF_DASHBOARD_CACHE_SECONDS = int(os.getenv('STAFF_DASHBOARD_CACHE_SECONDS', '20'))

# Phase 4 payment settings remain disabled until the dedicated Stripe service
# and verified webhook lifecycle are enabled in a test environment.
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')
STRIPE_TEST_MODE = os.getenv('STRIPE_TEST_MODE', 'True').lower() == 'true'
DELIVERY_FEE_LKR = Decimal(os.getenv('DELIVERY_FEE_LKR', '0.00'))
DELIVERY_BASE_FEE_LKR = Decimal(os.getenv('DELIVERY_BASE_FEE_LKR', '150.00'))
DELIVERY_RATE_PER_KM_LKR = Decimal(os.getenv('DELIVERY_RATE_PER_KM_LKR', '80.00'))
DELIVERY_ESTIMATE_HOURS = int(os.getenv('DELIVERY_ESTIMATE_HOURS', '24'))
STORE_LATITUDE = os.getenv('STORE_LATITUDE', '6.9271')
STORE_LONGITUDE = os.getenv('STORE_LONGITUDE', '79.8612')
LOCATION_API_BASE_URL = os.getenv('LOCATION_API_BASE_URL', 'https://locatesrilanka.herokuapp.com').rstrip('/')


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Authentication
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/manage/'
LOGOUT_REDIRECT_URL = '/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
